[build]
  command = "pnpm run build:aseprite && pnpm run build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@cornerstonejs/codec-libjpeg-turbo-8bit"]
  included_files = ["./node_modules/@cornerstonejs/codec-libjpeg-turbo-8bit/dist/*"]
