const crawlercheck_ai = [
  "AI2Bot",
  "Ai2Bot-Dolma",
  "Big-Sur-AI",
  "ChatGPT-Operator",
  "ChatGPT-User",
  "Claude-Code",
  "Claude-User",
  "ClaudeBot",
  "DeepSeekBot",
  "DigitalOceanGenAICrawler",
  "Duckassistbot",
  "GPTBot",
  "Google-Extended",
  "Grok",
  "GrokBot",
  "Liner Bot",
  "MistralAI-User",
  "MyCentralAIScraperBot",
  "PanguBot",
  "Perplexity-User",
  "PerplexityBot",
  "SBIntuitionsBot",
  "YouBot",
  "anthropic-ai",
  "cohere-ai",
  "cohere-training-data-crawler",
  "img2dataset",
  "quillbot-com",
];

const knownagents_ai_data_scrapers = [
  "AI2Bot",
  "Ai2Bot-Dolma",
  "Amazonbot",
  "Applebot-Extended",
  "bedrockbot",
  "Bytespider",
  "CCBot",
  "ChatGLM-Spider",
  "ClaudeBot",
  "CloudVertexBot",
  "cohere-training-data-crawler",
  "CohereBot",
  "Cotoyogi",
  "Datenbank Crawler",
  "DeepSeekBot",
  "Doubaobot",
  "ERNIEBot",
  "FacebookBot",
  "Google-Extended",
  "GoogleOther",
  "GPTBot",
  "ICC-Crawler",
  "imageSpider",
  "Kangaroo Bot",
  "KimiBot",
  "KimiCrawler",
  "laion-huggingface-processor",
  "LCC",
  "meta-externalagent",
  "micro-crawl",
  "MistralBot",
  "MoonshotBot",
  "MoonSpider",
  "netEstate Imprint Crawler",
  "omgili",
  "PanguBot",
  "peer39_crawler",
  "QwenBot",
  "SalamandraVLM",
  "SBIntuitionsBot",
  "Spider",
  "Timpibot",
  "VelenPublicWebCrawler",
  "webzio-extended",
];

const knownagents_ai_data_providers = [
  "AIWebIndex",
  "ApifyBot",
  "ApifyWebsiteContentCrawler",
  "Bravebot",
  "Brightbot",
  "CragCrawler",
  "Crawlspace",
  "Diffbot",
  "ExaBot",
  "FirecrawlAgent",
  "HenkBot",
  "Mozilla-Tabstack",
  "Querit-SearchBot",
  "QueritBot",
  "ShapBot",
  "TavilyBot",
  "Terra Cotta",
  "TerraCotta",
  "YouBot",
];

export default class {
  async data() {
    return {
      permalink: "/robots.txt",
      eleventyExcludeFromCollections: true,
      layout: false,
    };
  }

  async render() {
    const userAgents = new Set([
      ...crawlercheck_ai,
      ...knownagents_ai_data_scrapers,
      ...knownagents_ai_data_providers,
    ]);

    return [...userAgents].join("\nDisallow: \/\n") + "\nDisallow: \/";
  }
}
